### ISSUE TITLE
BufferedInputStream is closed in PropertyBoxParserImpl

### ISSUE THREAD

**Issue by bhatiyajayesh** [copiousfreetime/mp4parser#2]
I got error in Mp4Parser Library, This lib can not read properly InputStream in Samsung J5 not tested other device.

```
InputStream is = new BufferedInputStream(getClass()
				.getResourceAsStream("/isoparser-default.properties"));
```
I got error [at PropertyBoxParserImpl.java#L43](https://github.com/copiousfreetime/mp4parser/blob/master/isoparser/src/main/java/com/coremedia/iso/PropertyBoxParserImpl.java#L43) . how to  solve it?

```
07-06 12:19:03.447: E/RuntimeException(16946): java.io.IOException: BufferedInputStream is closed
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.InputStreamReader.read(InputStreamReader.java:233)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.BufferedReader.readChar(BufferedReader.java:263)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.io.BufferedReader.read(BufferedReader.java:253)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.util.Properties.load(Properties.java:289)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.util.Properties.load(Properties.java:248)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.coremedia.iso.PropertyBoxParserImpl.<init>(PropertyBoxParserImpl.java:47)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.coremedia.iso.IsoFile.createBoxParser(IsoFile.java:96)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.coremedia.iso.IsoFile.<init>(IsoFile.java:44)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:55)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:42)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.birthdaysong.activity.RecordActivity$mergeMusic.doInBackground(RecordActivity.java:275)
07-06 12:19:03.447: E/RuntimeException(16946): 	at com.birthdaysong.activity.RecordActivity$mergeMusic.doInBackground(RecordActivity.java:1)
07-06 12:19:03.447: E/RuntimeException(16946): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 12:19:03.447: E/RuntimeException(16946): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-06 12:19:03.447: E/RuntimeException(16946): 	at java.lang.Thread.run(Thread.java:818) 
```

**Comment by copiousfreetime** [comment]
@bhatiyajayesh This is an old fork of the pre-github-migration mp4parser from google code. You really should be looking at https://github.com/sannies/mp4parser instead.
